# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34ec5d5853a74b98cfa016b37ff0f8746facf14c23fce6a4a6257b66c9115913543c1b7c422f12b72e2ab6066fe96c5a9d10c0b7c43632ecae1bbd50b9c3eb7

test:
  secret_key_base: c8a94ca0c1d31a960af75ea5a3c06160a24ddaf31418ef126493aef14ebed66826ce14668f55d9626f7870d75fd69244eb63dca49522de0367099f3cfed6e512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
